version: '3'

services:
  rustsite:
    image: kevinvdburgt/rust-server
    container_name: rustsite
    restart: unless-stopped
    environment:
      # Reverse ngnix proxy
      VIRTUAL_HOST: rust.gamelimits.com
      VIRTUAL_PORT: 7777
      LETSENCRYPT_HOST: rust.gamelimits.com
      LETSENCRYPT_EMAIL: info@gamelimits.com
    volumes:
      - ./config.js:/app/config.js:ro

  mysql:
    image: mariadb
    container_name: rustsite-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: random0uytsdjghs
      MYSQL_DATABASE: gamelimmits_rust
      MYSQL_USER: gamelimits
      MYSQL_PASSWORD: osduhfgp9as7d8yasd
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./database:/var/lib/mysql

networks:
  default:
    external:
      name: webproxy
